<a href="https://colab.research.google.com/github/anacvelarde-blip/CursoPhytonProinnova/blob/main/Proyecto_3_Admitidos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Proyecto 3 Seleccion de Aspiramntes en Proceso de Admisi√≥n
pyhthon Proinnova
Ana Laura Chavez Velarde
CUCSH

In [1]:

# ruta de archivo
ruta_archivo = "/content/drive/MyDrive/Phyton Proinnova 2025B/applicant_list_7.txt"# conectar con drive
from google.colab import drive
drive.mount('/content/drive')

# Importar pandas
import pandas as pd

nombre_columnas = ["Nombre", "Apellido", "EPH", "ECH", "EMA", "ECS", "ESP", "OP1", "OP2", "OP3" ]

df = pd.read_csv(ruta_archivo, sep=" ",names=nombre_columnas)
df

Mounted at /content/drive

,Nombre,Apellido,EPH,ECH,EMA,ECS,ESP,OP1,OP2,OP3
0,Jermine,Brunton,84,81,73,92,48,Physics,Engineering,Mathematics
1,Justo,Mirfin,71,77,61,60,41,Engineering,Biotech,Chemistry
2,Uzma,Naysmythe,60,94,75,71,80,Chemistry,Engineering,Mathematics
3,Koury,Wingo,71,81,81,83,59,Engineering,Biotech,Mathematics
4,Kentrell,Hillhouse,40,69,42,58,20,Mathematics,Engineering,Biotech
...,...,...,...,...,...,...,...,...,...,...
93,Tamkia,Fish,81,71,73,86,78,Physics,Engineering,Mathematics
94,Deniz,Blanchard,71,77,61,60,61,Engineering,Biotech,Chemistry
95,Mira,Riley,60,94,75,71,80,Engineering,Biotech,Mathematics
96,Loura,Macansh,71,81,81,93,79,Engineering,Physics,Mathematics
97,Nastassja,Trustram,60,49,82,68,70,Mathematics,Engineering,Physics

In [ ]:
print(df.shape)
df.info()

(98, 11)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 98 entries, 0 to 97
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Nombre           98 non-null     object
 1   Apellido         98 non-null     object
 2   EPH              98 non-null     int64
 3   ECH              98 non-null     int64
 4   EMA              98 non-null     int64
 5   ECS              98 non-null     int64
 6   ESP              98 non-null     int64
 7   OP1              98 non-null     object
 8   OP2              98 non-null     object
 9   OP3              98 non-null     object
 10  nombre_completo  98 non-null     object
dtypes: int64(5), object(6)
memory usage: 8.6+ KB

In [ ]:
df['nombre_completo'] = df['Nombre'] + ' ' + df['Apellido']
display(df)

,Nombre,Apellido,EPH,ECH,EMA,ECS,ESP,OP1,OP2,OP3,nombre_completo
0,Jermine,Brunton,84,81,73,92,48,Physics,Engineering,Mathematics,Jermine Brunton
1,Justo,Mirfin,71,77,61,60,41,Engineering,Biotech,Chemistry,Justo Mirfin
2,Uzma,Naysmythe,60,94,75,71,80,Chemistry,Engineering,Mathematics,Uzma Naysmythe
3,Koury,Wingo,71,81,81,83,59,Engineering,Biotech,Mathematics,Koury Wingo
4,Kentrell,Hillhouse,40,69,42,58,20,Mathematics,Engineering,Biotech,Kentrell Hillhouse
...,...,...,...,...,...,...,...,...,...,...,...
93,Tamkia,Fish,81,71,73,86,78,Physics,Engineering,Mathematics,Tamkia Fish
94,Deniz,Blanchard,71,77,61,60,61,Engineering,Biotech,Chemistry,Deniz Blanchard
95,Mira,Riley,60,94,75,71,80,Engineering,Biotech,Mathematics,Mira Riley
96,Loura,Macansh,71,81,81,93,79,Engineering,Physics,Mathematics,Loura Macansh
97,Nastassja,Trustram,60,49,82,68,70,Mathematics,Engineering,Physics,Nastassja Trustram

In [ ]:
# definici√≥n de una funcion  para estimar puntaje de admisi√≥n
def calcular_puntaje_admision(linea, opcion):
  puntaje = 0
  departamento = linea[opcion]
  if departamento == "Physics":
    puntaje = (linea["EPH"] + linea["EMA"] +linea["ESP"]) /3
  elif departamento == "Mathematics":
    puntaje = (linea["ECH"] + linea["ECS"]) + linea["ESP"] /3
  elif departamento == "Engineering":
    puntaje = (linea["EMA"] + linea["ECS"] + linea["EPH"] + linea["ESP"]) /4
  elif departamento == "Chemistry":
    puntaje = (linea["ECH"] + linea["EPH"]) + linea["ESP"] /3
  elif departamento == "Biotech":
    puntaje = (linea["EMA"] + linea["ECS"] + linea["ECH"] +linea["ESP"]) /4
  else:
    return None
  return round(puntaje, 2)

df['OP1_score'] = df.apply(lambda x: calcular_puntaje_admision(x, 'OP1'), axis=1)
df['OP2_score'] = df.apply(lambda x: calcular_puntaje_admision(x, 'OP2'), axis=1)
df['OP3_score'] = df.apply(lambda x: calcular_puntaje_admision(x, 'OP3'), axis=1)

display(df)

,Nombre,Apellido,EPH,ECH,EMA,ECS,ESP,OP1,OP2,OP3,nombre_completo,OP1_score,OP2_score,OP3_score
0,Jermine,Brunton,84,81,73,92,48,Physics,Engineering,Mathematics,Jermine Brunton,68.33,74.25,189.00
1,Justo,Mirfin,71,77,61,60,41,Engineering,Biotech,Chemistry,Justo Mirfin,58.25,59.75,161.67
2,Uzma,Naysmythe,60,94,75,71,80,Chemistry,Engineering,Mathematics,Uzma Naysmythe,180.67,71.50,191.67
3,Koury,Wingo,71,81,81,83,59,Engineering,Biotech,Mathematics,Koury Wingo,73.50,76.00,183.67
4,Kentrell,Hillhouse,40,69,42,58,20,Mathematics,Engineering,Biotech,Kentrell Hillhouse,133.67,40.00,47.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,Tamkia,Fish,81,71,73,86,78,Physics,Engineering,Mathematics,Tamkia Fish,77.33,79.50,183.00
94,Deniz,Blanchard,71,77,61,60,61,Engineering,Biotech,Chemistry,Deniz Blanchard,63.25,64.75,168.33
95,Mira,Riley,60,94,75,71,80,Engineering,Biotech,Mathematics,Mira Riley,71.50,80.00,191.67
96,Loura,Macansh,71,81,81,93,79,Engineering,Physics,Mathematics,Loura Macansh,81.00,77.00,200.33
97,Nastassja,Trustram,60,49,82,68,70,Mathematics,Engineering,Physics,Nastassja Trustram,140.33,70.00,70.67

In [ ]:
# definici√≥n de una funcion  para estimar puntaje de admisi√≥n
def calcular_puntaje_admision(linea, opcion):
  puntaje = 0
  departamento = linea[opcion]
  if departamento == "Physics":
    puntaje = (linea["EPH"] + linea["EMA"] +linea["ESP"]) /3
  elif departamento == "Chemistry":
    puntaje = (linea["ECH"] + linea["ECS"]) /3
  return puntaje

In [ ]:
N = int(input("Ingrese el cupo maximo por departamento: "))
departamento_seleccionado = input("Ingrese el departamento: ")

Ingrese el cupo maximo por departamento: 10
Ingrese el departamento: Biotech

In [3]:
# Get input from the user for capacity and department
N = int(input("Ingrese el cupo maximo por departamento: "))
departamento_seleccionado = input("Ingrese el departamento: ")

# definici√≥n de una funcion  para estimar puntaje de admisi√≥n
def calcular_puntaje_admision(linea, opcion):
  puntaje = 0
  departamento = linea[opcion]
  if departamento == "Physics":
    puntaje = (linea["EPH"] + linea["EMA"] +linea["ESP"]) /3
  elif departamento == "Mathematics":
    puntaje = (linea["ECH"] + linea["ECS"]) + linea["ESP"] /3
  elif departamento == "Engineering":
    puntaje = (linea["EMA"] + linea["ECS"] + linea["EPH"] + linea["ESP"]) /4
  elif departamento == "Chemistry":
    puntaje = (linea["ECH"] + linea["EPH"]) + linea["ESP"] /3
  elif departamento == "Biotech":
    puntaje = (linea["EMA"] + linea["ECS"] + linea["ECH"] +linea["ESP"]) /4
  else:
    return None
  return round(puntaje, 2)

# Filter applicants who selected the chosen department as one of their options
df_filtered = df[(df['OP1'] == departamento_seleccionado) | (df['OP2'] == departamento_seleccionado) | (df['OP3'] == departamento_seleccionado)].copy()

# Calculate the score for the selected department for each filtered applicant
def calcular_puntaje_departamento(row, departamento):
    if row['OP1'] == departamento:
        return calcular_puntaje_admision(row, 'OP1')
    elif row['OP2'] == departamento:
        return calcular_puntaje_admision(row, 'OP2')
    elif row['OP3'] == departamento:
        return calcular_puntaje_admision(row, 'OP3')
    return None


df_filtered['Puntaje_Departamento'] = df_filtered.apply(lambda row: calcular_puntaje_departamento(row, departamento_seleccionado), axis=1)

display(df_filtered)

Ingrese el cupo maximo por departamento: 10
Ingrese el departamento: Mathematics

,Nombre,Apellido,EPH,ECH,EMA,ECS,ESP,OP1,OP2,OP3,Puntaje_Departamento
0,Jermine,Brunton,84,81,73,92,48,Physics,Engineering,Mathematics,189.00
2,Uzma,Naysmythe,60,94,75,71,80,Chemistry,Engineering,Mathematics,191.67
3,Koury,Wingo,71,81,81,83,59,Engineering,Biotech,Mathematics,183.67
4,Kentrell,Hillhouse,40,69,42,58,20,Mathematics,Engineering,Biotech,133.67
5,Trica,Macalpine,75,80,96,88,66,Engineering,Mathematics,Biotech,190.00
...,...,...,...,...,...,...,...,...,...,...,...
92,Ehab,Cocciardi,75,73,84,97,82,Engineering,Biotech,Mathematics,197.33
93,Tamkia,Fish,81,71,73,86,78,Physics,Engineering,Mathematics,183.00
95,Mira,Riley,60,94,75,71,80,Engineering,Biotech,Mathematics,191.67
96,Loura,Macansh,71,81,81,93,79,Engineering,Physics,Mathematics,200.33
97,Nastassja,Trustram,60,49,82,68,70,Mathematics,Engineering,Physics,140.33

In [4]:
df_sorted = df_filtered.sort_values(by='Puntaje_Departamento', ascending=False)
display(df_sorted)

,Nombre,Apellido,EPH,ECH,EMA,ECS,ESP,OP1,OP2,OP3,Puntaje_Departamento
47,Kennedy,Barrett,77,93,84,87,94,Chemistry,Biotech,Mathematics,211.33
23,Meshell,Otway-Ruthven,75,73,84,97,94,Engineering,Biotech,Mathematics,201.33
81,Ayeshia,Jackman,80,85,73,86,89,Chemistry,Physics,Mathematics,200.67
33,Dashanna,Herron,80,85,73,86,89,Physics,Chemistry,Mathematics,200.67
15,Marlynn,Favell,71,81,81,93,79,Engineering,Biotech,Mathematics,200.33
...,...,...,...,...,...,...,...,...,...,...,...
82,Jordann,Rives,84,61,88,62,60,Mathematics,Chemistry,Biotech,143.00
77,Ramina,Ogilvie,80,65,70,68,29,Mathematics,Engineering,Biotech,142.67
97,Nastassja,Trustram,60,49,82,68,70,Mathematics,Engineering,Physics,140.33
4,Kentrell,Hillhouse,40,69,42,58,20,Mathematics,Engineering,Biotech,133.67
69,Teneil,Maclean,85,63,84,45,69,Mathematics,Physics,Chemistry,131.00